#!/bin/bash

pid=$(cat $HOME/.xurfaced/pid)

plugins=$HOME/.xurfaced/plugins/list

if [ -e $plugins ]; then
    cat $plugins | sed -r "s:(.*):$HOME/.xurfaced/sethead \1:"
    echo "";
fi

echo "$HOME/.xurfaced/sethead system"
echo "$HOME/.xurfaced/quit"
