#!/bin/bash

pid=$(cat $HOME/.halo/pid)

echo "$HOME/.halo/sethead videos"
echo "$HOME/.halo/sethead music"
echo "$HOME/.halo/sethead games"
cat $HOME/.halo/plugins/list | sed -r "s:(.*):$HOME/.halo/sethead \1:"
echo ""
echo "$HOME/.halo/sethead system"
echo "$HOME/.halo/quit"
