#!/bin/bash

if [ "$1" = "" ]; then
    exit;
fi

target="$HOME/.xurfaced"
repository="$(cat $HOME/.xurfaced/plugins/repository)"

mkdir "$target/$1"

if [ $? -ne 0 ]; then
    exit;
fi

echo $1 >> $HOME/.xurfaced/plugins/list
curl -s $repository/$1/title -o $target/$1/title
chmod +x $target/$1/title
curl -s $repository/$1/desc -o $target/$1/desc
curl -s $repository//$1/exec -o $target/$1/exec
chmod +x $target/$1/exec
$HOME/.xurfaced/sethead main
