#!/bin/bash

if [ "$1" = "" ]; then
    exit;
fi

target="$HOME/.xurfaced"
repository="$(cat $HOME/.xurfaced/plugins/repository)"

mkdir "$target/$1"

if [ $? -ne 0 ]; then
    exit;
fi

echo $1 >> $HOME/.xurfaced/plugins/list
curl -s $repository/$1.install -o $HOME/.xurfaced/plugins/$1.install
chmod +x $HOME/.xurfaced/plugins/$1.install
$HOME/.xurfaced/plugins/$1.install $target/$1 $repository/$1
$HOME/.xurfaced/sethead main
