#!/bin/bash

cwd="$HOME/.halo/browse/cwd"
path=$(cat $cwd)
parent=$(dirname $path)
titles=$(ls -1 $path)

echo "$HOME/.halo/sethead main"
echo ""
echo "$HOME/.halo/browse/setcwd $parent"
ls -1F $path | sort | sed -r "s:(.*):$HOME/.halo/browse/setcwd $path/\1:" | sed -r "s:(.*)[^/]$::"

